spring.application.name=finatiol-notificaciones-ms

spring.config.import=optional:configserver:http://localhost:8888

server.port=8083

eureka.client.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=finatiols@gmail.com

spring.mail.password=otna tnua owpe hwzr

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs